### PR TITLE
Feat: Support multiple tag rows for each tag exported

### PR DESCRIPTION
**Pull request by cluedindev**
I have added the ability for SQL Server to now loop over Tags collections and create a row in SQL per Tag.

### CODE REVIEW

**Review by Kieranties — CHANGES_REQUESTED** [review]
@cluedindev Is that what _all_ customers want or just one customer?
Wouldn't this make more sense to push tags to a separate table as now the main table can grow exponentially depending on the tags.

Should we consider additional collection fields? Or will we manage those on a case by case basis?

This feels like we should support extra modelling options when selecting the field rather than specific implementations

**Comment by cluedindev** [comment]
This is just for one customer for now as I put through another ticket highlighting that this won't scale with building new SQL Server Connectors per customer and hence the logic of collections should move to the core and we should be able to specify a uniqueness constraint so that we know what MERGE command has to run in SQL Connection. 

It could also be (like you said) that we actually spit all collections out to their own tables. I am all for that as well.  In saying that, I think people will want choice on what it does so we don't get into the same problem again where we have to build different SQL Server Connectors for each customer.

**Comment by BenFidge** [comment]
@Kieranties Might be a nice self-contained task for Nick to take all this and make Sql Connector much more configurable

**Comment by Kieranties** [comment]
This _must_ be implemented as a customer specific feature, not in the main repo as it is a customer specific adaption. See the Semler connector for details: https://github.com/CluedIn-io/CluedIn.Connector.SqlServer.Semler/blob/release/1.0/src/Connector.SqlServer.Semler/Features/ExpandBuildStoreDataFeature.cs

**Pull request closed without merging**
